const suratFormat = {
  'Keterangan Usaha': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'Jenis Usaha' },
    { no: 10, field: 'Tempat Usaha' }
  ],
  'SKCK': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'Jenis Kebutuhan' }
  ],
  'Rekom BBM Solar': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'Jenis Alat' },
    { no: 10, field: 'Konsumen Pengguna' },
    { no: 11, field: 'Fungsi Alat' }
  ],
  'Rekom BBM Pertalite': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'Jenis Alat' },
    { no: 10, field: 'Konsumen Pengguna' },
    { no: 11, field: 'Fungsi Alat' }
  ],
  'Keterangan Kematian': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'Hari/Tgl Meninggal' },
    { no: 10, field: 'Waktu Meninggal' },
    { no: 11, field: 'Sebab Meninggal' },
    { no: 12, field: 'Tempat Meninggal' }
  ],
  'Keterangan Domisili': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' }
  ],
  'Keterangan Domisili Organisasi': [
    { no: 1, field: 'Nama Organisasi' },
    { no: 2, field: 'Pimpinan Organisasi' },
    { no: 3, field: 'Alamat Lengkap' },
    { no: 4, field: 'Dusun' },
  ],
  'Keterangan Tidak Mampu Umum': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' }
  ],
  'Keterangan Tidak Mampu Dengan Penghasilan Orang Tua': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'Penghasilan Orang Tua' }
  ],
  'Keterangan Satu Nama Umum': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'Nama Berkas' },
    { no: 10, field: 'Nama Lain' }
  ],
  'Keterangan Satu Nama Khusus': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'Nama Lain' },
    { no: 10, field: 'Nama Kelompok Tani' }
  ],
  'Keterangan Asal Usul': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'NIK Suami/Istri' },
    { no: 10, field: 'Nama Suami/Istri' },
    { no: 11, field: 'Tempat/Tgl Lahir Suami/Istri' },
    { no: 12, field: 'Jenis Kelamin Suami/Istri' },
    { no: 13, field: 'Alamat Suami/Istri' },
    { no: 14, field: 'RT/RW Suami/Istri' },
    { no: 15, field: 'Agama Suami/Istri' },
    { no: 16, field: 'Pekerjaan Suami/Istri' }
  ],
  'Keterangan Pindah Domisili': [
    { no: 1, field: 'NIK' },
    { no: 2, field: 'Nama' },
    { no: 3, field: 'Tempat/Tgl Lahir' },
    { no: 4, field: 'Jenis Kelamin' },
    { no: 5, field: 'Alamat' },
    { no: 6, field: 'RT/RW' },
    { no: 7, field: 'Agama' },
    { no: 8, field: 'Pekerjaan' },
    { no: 9, field: 'No KK' },
    { no: 10, field: 'Nama Kepala Keluarga' },
    { no: 11, field: 'Alamat Tujuan' },
    { no: 12, field: 'No KK Tujuan' },
    { no: 13, field: 'Desa/Keluarahan Tujuan' },
    { no: 14, field: 'Kecamatan/Kota Tujuan' },
    { no: 15, field: 'Kabupaten Tujuan' },
    { no: 16, field: 'Provinsi Tujuan' },
    { no: 17, field: 'Jumlah Keluarga Yg Pindah' },
  ],
  'Keterangan Kuasa': [
    { no: 1, field: 'NIK Pemberi Kuasa' },
    { no: 2, field: 'Nama Pemberi Kuasa' },
    { no: 3, field: 'Tempat/Tgl Lahir Pemberi Kuasa' },
    { no: 4, field: 'Jenis Kelamin Pemberi Kuasa' },
    { no: 5, field: 'Alamat Pemberi Kuasa' },
    { no: 6, field: 'RT/RW Pemberi Kuasa' },
    { no: 7, field: 'Agama Pemberi Kuasa' },
    { no: 8, field: 'Pekerjaan Pemberi Kuasa' },
    { no: 9, field: 'Jenis Kuasa' },
    { no: 10, field: 'NIK Penerima Kuasa' },
    { no: 11, field: 'Nama Penerima Kuasa' },
    { no: 12, field: 'Tempat/Tgl Lahir Penerima Kuasa' },
    { no: 13, field: 'Jenis Kelamin Penerima Kuasa' },
    { no: 14, field: 'Alamat Penerima Kuasa' },
    { no: 15, field: 'RT/RW Penerima Kuasa' },
    { no: 16, field: 'Agama Penerima Kuasa' },
    { no: 17, field: 'Pekerjaan Penerima Kuasa' }
  ],
  'Pemberitahuan': [
    { no: 1, field: 'Perihal Pemberitahuan' },
    { no: 2, field: 'Tanggal Kegiatan' },
    { no: 3, field: 'Waktu Kegiatan' },
    { no: 4, field: 'Tempat Kegiatan' }
  ],
  'Undangan': [
    { no: 1, field: 'Sifat' },
    { no: 2, field: 'Tujuan' },
    { no: 3, field: 'Lampiran' },
    { no: 4, field: 'Perihal' },
    { no: 5, field: 'Acara' },
    { no: 6, field: 'Hari/Tanggal Pelaksanaan' },
    { no: 7, field: 'Waktu Pelaksanaan' },
    { no: 8, field: 'Tempat Pelaksanaan' },
    { no: 9, field: 'Alamat Pelaksanaan' }
  ],
  'Surat Perintah Tugas': [
    { no: 1, field: 'Dasar' },
    { no: 2, field: 'NIK' },
    { no: 3, field: 'Nama' },
    { no: 4, field: 'Tempat/Tgl Lahir' },
    { no: 5, field: 'Jenis Kelamin' },
    { no: 6, field: 'Alamat' },
    { no: 7, field: 'RT/RW' },
    { no: 8, field: 'Agama' },
    { no: 9, field: 'Pekerjaan' },
    { no: 10, field: 'Jabatan/Posisi' },
    { no: 11, field: 'Untuk' },
    { no: 12, field: 'Pada' },
    { no: 13, field: 'Di' }
  ],
  'Custom': [
    { no: 1, field: 'Nama Surat' },
    { no: 2, field: 'Isi Surat' },
  ]
};
const jenisSuratKeluar = [
  'Keterangan Usaha', 'SKCK', 'Rekom BBM Solar', 'Rekom BBM Pertalite', 'Keterangan Kematian', 'Keterangan Domisili', 'Keterangan Domisili Organisasi', 'Keterangan Tidak Mampu Umum', 'Keterangan Tidak Mampu Dengan Penghasilan Orang Tua', 'Keterangan Satu Nama Umum', 'Keterangan Satu Nama Khusus', 'Keterangan Asal Usul', 'Keterangan Pindah Domisili', 'Keterangan Kuasa', 'Pemberitahuan'
];
module.exports = { suratFormat, jenisSuratKeluar };